# Docker Compose for Sales SaaS Development
# Note: This setup uses Supabase for backend services
# The main development workflow uses `supabase start` instead of Docker

version: '3.8'

services:
  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sales-saas-frontend
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=http://host.docker.internal:54321
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - sales-saas-network
    command: npm run dev

networks:
  sales-saas-network:
    driver: bridge
